before_all do
  ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
end

lane :test do
  # upload to Firebase Test Lab
  firebase_test_lab_android(
    project_id: "cats-234205",
    gcloud_service_key_file: "fastlane/client-secret.json",
    gcloud_components_channel: "alpha",
    type: "instrumentation",
    devices: [
      {
        model: "NexusLowRes",
        version: "27",
        locale: "ja_JP",
        orientation: "portrait"
      },
      {
        model: "Pixel2",
        version: "28"
      }
    ],
    app_apk: "~/Desktop/i-app.apk" ,
    app_test_apk: "~/Desktop/i-androidTest.apk",
    console_log_file_name: "log/console_output.log",
    timeout: "3m",
    firebase_test_lab_results_bucket: "firebase_cats_test_bucket_pr8",
    slack_url: ENV["SLACK_URL"],
    download_dir: ".results",
    github_owner: "cats-oss",
    github_repository: "fastlane-plugin-firebase_test_lab_android",
    github_pr_number: "8",
    github_api_token: "fd4e560da02c76f53e15ce26eb73a94181de54bc"
  )
end
